function a() { return fui.apply('a', arguments); }
function article() { return fui.apply('article', arguments); }
function aside() { return fui.apply('aside', arguments); }
function b() { return fui.apply('b', arguments); }
function body() { return fui.apply('body', arguments); }
function br() { return fui.apply('br', arguments); }
function button() { return fui.apply('button', arguments); }
function canvas() { return fui.apply('canvas', arguments); }
function caption() { return fui.apply('caption', arguments); }
function col() { return fui.apply('col', arguments); }
function colgroup() { return fui.apply('colgroup', arguments); }
function data() { return fui.apply('data', arguments); }
function datalist() { return fui.apply('datalist', arguments); }
function dd() { return fui.apply('dd', arguments); }
function del() { return fui.apply('del', arguments); }
function details() { return fui.apply('details', arguments); }
function dfn() { return fui.apply('dfn', arguments); }
function dialog() { return fui.apply('dialog', arguments); }
function div() { return fui.apply('div', arguments); }
function dl() { return fui.apply('dl', arguments); }
function dt() { return fui.apply('dt', arguments); }
function em() { return fui.apply('em', arguments); }
function embed() { return fui.apply('embed', arguments); }
function fieldset() { return fui.apply('fieldset', arguments); }
function footer() { return fui.apply('footer', arguments); }
function form() { return fui.apply('form', arguments); }
function h1() { return fui.apply('h1', arguments); }
function h2() { return fui.apply('h2', arguments); }
function h3() { return fui.apply('h3', arguments); }
function h4() { return fui.apply('h4', arguments); }
function h5() { return fui.apply('h5', arguments); }
function h6() { return fui.apply('h6', arguments); }
function head() { return fui.apply('head', arguments); }
function header() { return fui.apply('header', arguments); }
function hgroup() { return fui.apply('hgroup', arguments); }
function hr() { return fui.apply('hr', arguments); }
function html() { return fui.apply('html', arguments); }
function i() { return fui.apply('i', arguments); }
function iframe() { return fui.apply('iframe', arguments); }
function img() { return fui.apply('img', arguments); }
function input() { return fui.apply('input', arguments); }
function label() { return fui.apply('label', arguments); }
function legend() { return fui.apply('legend', arguments); }
function li() { return fui.apply('li', arguments); }
function main() { return fui.apply('main', arguments); }
function nav() { return fui.apply('nav', arguments); }
function object() { return fui.apply('object', arguments); }
function ol() { return fui.apply('ol', arguments); }
function optgroup() { return fui.apply('optgroup', arguments); }
function option() { return fui.apply('option', arguments); }
function output() { return fui.apply('output', arguments); }
function p() { return fui.apply('p', arguments); }
function pre() { return fui.apply('pre', arguments); }
function q() { return fui.apply('q', arguments); }
function section() { return fui.apply('section', arguments); }
function select() { return fui.apply('select', arguments); }
function small() { return fui.apply('small', arguments); }
function span() { return fui.apply('span', arguments); }
function strike() { return fui.apply('strike', arguments); }
function strong() { return fui.apply('strong', arguments); }
function sub() { return fui.apply('sub', arguments); }
function summary() { return fui.apply('summary', arguments); }
function sup() { return fui.apply('sup', arguments); }
function table() { return fui.apply('table', arguments); }
function tbody() { return fui.apply('tbody', arguments); }
function td() { return fui.apply('td', arguments); }
function textarea() { return fui.apply('textarea', arguments); }
function tfoot() { return fui.apply('tfoot', arguments); }
function th() { return fui.apply('th', arguments); }
function thead() { return fui.apply('thead', arguments); }
function title() { return fui.apply('title', arguments); }
function tr() { return fui.apply('tr', arguments); }
function u() { return fui.apply('u', arguments); }
function ul() { return fui.apply('ul', arguments); }